# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracles', '0004_auto_20160815_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='abi',
            field=models.TextField(default=''),
        ),
    ]
