# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracles', '0007_auto_20160817_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='interface',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interface',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
