# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracles', '0009_remove_i_o_indexed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i_o',
            options={'ordering': ()},
        ),
        migrations.RemoveField(
            model_name='i_o',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='i_o',
            name='outputs',
        ),
        migrations.AddField(
            model_name='interface',
            name='inputs',
            field=models.ManyToManyField(related_name='inputs', to='oracles.I_O'),
        ),
        migrations.AddField(
            model_name='interface',
            name='outputs',
            field=models.ManyToManyField(related_name='outputs', to='oracles.I_O'),
        ),
    ]
