# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('public_key', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('public_key',),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrated', models.DateTimeField(auto_now_add=True)),
                ('public_key', models.CharField(max_length=100)),
                ('multisig_adddress', models.CharField(max_length=100)),
                ('redeem_script', models.CharField(max_length=256)),
                ('proposal', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Proposal')),
            ],
            options={
                'ordering': ('registrated',),
            },
        ),
    ]
