# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='multisig_adddress',
            new_name='multisig_address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='public_key',
        ),
    ]
