# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160810_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Proposal'),
        ),
    ]
