# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oracles', '0002_auto_20160815_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracle',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oracles', to='oracles.Contract'),
        ),
    ]
