# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracles', '0003_auto_20160815_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracle',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='oracles',
            field=models.TextField(default=''),
        ),
    ]
